repos:
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.49.2
    hooks:
      - id: cfn-lint
        language_version: python3.13
        files: '^docs/assets/.*cloudformation.*\.ya?ml$'
